#!/usr/bin/env bash
# ALPHA - UserBot
# Copyright (C) 2021-2022 Cultured_Heaven
#
# This file is a part of < https://github.com/Light-Sensei/AlphaUB/ >
# PLease read the GNU Affero General Public License in <https://www.github.com/Light-Sensei/AlphaUB/blob/main/LICENSE/>.

if [ -d "resources" ]
then
    echo "Current directory Identified.."
else
    apt install git -y
    git clone https://github.com/Light-Sensei/AlphaUB
    cd ALPHA
fi
bash resources/startup/termux.sh
