#!/usr/bin/env bash
# Ultroid - UserBot
# Copyright (C) 2021-2022 Cultured_Heaven
#
# This file is a part of < https://github.com/Cultured_Heaven/Ultroid/ >
# PLease read the GNU Affero General Public License in <https://www.github.com/Cultured_Heaven/Ultroid/blob/main/LICENSE/>.

if [ -d "resources" ]
then
    echo "Current directory Identified.."
else
    apt install git -y
    git clone https://github.com/Cultured_Heaven/Ultroid
    cd Ultroid
fi
bash resources/startup/termux.sh
