#!/usr/bin/env bash
# Ultroid - UserBot
# Copyright (C) 2021-2022 Cultured_Heaven
#
# This file is a part of < https://github.com/Cultured_Heaven/Ultroid/ >
# PLease read the GNU Affero General Public License in <https://www.github.com/Cultured_Heaven/Ultroid/blob/main/LICENSE/>.

bash resources/session/session.sh
